### ISSUE TITLE
Checklist para testear de Alcance del Rol Dueño/Administrador

### ISSUE THREAD

**Issue by MaxiBarbo** [MaxiBarbo/challengeTest1#44]
## **Resultados esperados:**
**1. Gestión de Clientes y Empleados**
   - [ ] Gestión de la información de clientes y empleados.
   - [ ] Verificar la capacidad de agregar, editar y eliminar registros de clientes y empleados.

**2. Control de Membresías y Pagos**
   - [ ] Verificar que pueda acceder a la información sobre las membresías de los clientes.
   - [ ] Verificar que pueda realizar acciones como renovar membresías, registrar pagos y enviar recordatorios de pagos pendientes.

**3. Gestión de Sedes y Profesores**
   - [ ] Verificar que se pueda visualizar y gestionar información sobre las sedes del gimnasio.
   - [ ] Verificar la capacidad de agregar, editar y eliminar sedes y profesores según sea necesario.

**4. Análisis de Finanzas, Estadísticas y Gestión de los Productos**
   - [ ] Verificar el acceso a la gestión y visualización del inventario de productos en la tienda del gimnasio.
   - [ ] Verificar la funcionalidad de compras (registros - ventas) y su correspondiente manejo de stock.

**5. Comunicación y Notificación**
   - [ ] Verificar la capacidad de enviar y recibir comentarios tanto de clientes como de profesores y empleados según sea necesario.
   - [ ] Verificar la capacidad de personalizar el contenido de las comunicaciones.

**6. Seguridad y Gestión de Acceso**
   - [ ] Verificar que el sistema de gestión de usuarios y roles funcione correctamente.
   - [ ] Probar la capacidad de asignar y revocar permisos según sea necesario.
